return { }

-- return {
-- 	"kevinhwhang91/nvim-ufo",
-- 	dependencies = {
-- 		"kevinhwang91/promise-async",
-- 	},
-- 	config = function()
-- 		vim.opt.foldcolumn = "0" -- don't show fold numbers
-- 		vim.opt.foldlevel = 99
-- 		vim.opt.foldlevelstart = 99
-- 		vim.opt.foldenable = true
--
-- 		vim.keymap.set("n", "zR", require("ufo").openAllFolds)
-- 		vim.keymap.set("n", "zM", require("ufo").closeAllFolds)
-- 		vim.keymap.set("n", "zK", function()
-- 			local winid = require("ufo").peekFoldedLinesUnderCursor()
-- 			if not winid then
-- 				vim.lsp.buf.hover()
-- 			end
-- 		end, { desc = "Peek Fold" })
--
-- 		require("ufo").setup({
-- 			provider_selector = function(bufnr, filetype, buftype)
-- 				return { "lsp", "indent" }
-- 			end,
-- 		})
-- 	end,
-- }
